version: 0.2.3.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: bFVGoXLR4/8VSClNH2s5qhXfJNwbJPbggNv6grvl+JaITuMkHLqvCw+48T0uKyFI
  RELEASE_KEY_PASSWORD:
    secure: 3+fpAMwxomiOZ5fzpb+3kjV4RvPSn0GRvFp71bZZs3QQr06zNU2Wvu4p77dmTKH+
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -ne "true") {
        # $blockRdp = $true
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    }
install:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
        nuget install secure-file -ExcludeVersion
        secure-file\tools\secure-file -decrypt GoogleTestExtension\Keys\Key_Release.snk.enc -secret $env:RELEASE_KEY_PASSWORD
    }
before_build: 
- cmd: >-
    cd GoogleTestAdapter

    SetVersion %APPVEYOR_BUILD_VERSION%

    cd TestAdapter.Tests

    IgnoreTests TestExecutorSequentialTests.cs::CancelingExecutorStopsTestExecution, TestExecutorParallelTests.cs::ParallelTestExecutionSpeedsUpTestExecution

    cd ..\..
- ps: nuget restore GoogleTestAdapter\GoogleTestAdapter.sln
build:
  project: GoogleTestAdapter\GoogleTestAdapter.sln
  parallel: true
  verbosity: normal
after_build:
- ps: >-
    $version = $env:APPVEYOR_BUILD_VERSION.SubString(0, $env:APPVEYOR_BUILD_VERSION.LastIndexOf("."))

    $sourceFile = (Resolve-Path ("GoogleTestAdapter\VsPackage\bin\" + $env:CONFIGURATION + "\GoogleTestAdapter.VsPackage.vsix")).ToString()

    $targetFile = $([IO.FileInfo]$sourceFile).DirectoryName + "\GoogleTestAdapter-" + $version + ".vsix"

    Copy-Item -Path $sourceFile -Destination $targetFile
test_script:
- ps: >-
    $opencover = (Resolve-Path "GoogleTestAdapter/packages/OpenCover.*/tools/OpenCover.Console.exe").ToString()

    $coveralls = (Resolve-Path "GoogleTestAdapter/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $opencover -register:user -target:VsTest.Console.exe "-targetargs:/logger:Appveyor GoogleTestAdapter\DiaResolver.Tests\bin\$env:CONFIGURATION\GoogleTestAdapter.DiaResolver.Tests.dll GoogleTestAdapter\Core.Tests\bin\$env:CONFIGURATION\GoogleTestAdapter.Core.Tests.dll GoogleTestAdapter\TestAdapter.Tests\bin\$env:CONFIGURATION\GoogleTestAdapter.TestAdapter.Tests.dll" "-filter:+[*]* -[*Tests]* -[GoogleTestAdapter..VsPackage]*DialogPage -[GoogleTestAdapter.VsPackage]*TestExtensionOptionsPage -[GoogleTestAdapter.DiaResolver]*StubMemoryStream -[FluentAssertions*]*" -output:OpenCover_CoverageData.xml -returntargetcode

    $TestExitCode = $LASTEXITCODE

    & $coveralls --opencover -i OpenCover_CoverageData.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --serviceName AppVeyor

    if ($TestExitCode -ne 0) {
        exit $TestExitCode
    }
artifacts:
- path: GoogleTestAdapter\VsPackage\bin\$(configuration)\GoogleTestAdapter-*.vsix
  name: GoogleTestAdapter
- path: OpenCover_CoverageData.xml
  name: OpenCover coverage data
deploy:
  provider: GitHub
  auth_token:
    secure: yRqT6kz8c9NZEuCUyBjKXvCLUNXcAc41F2Y4fa318ylBPaIcl38UNAK5Jt8MsNhs
  description: 'TODO provide release notes'
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true